### ISSUE TITLE
[Miner] Allow selection of specific GPUs

### ISSUE THREAD

**Issue by pricejn2** [EggPool/EggMinerGpu#5]
This is either a docs request or a new feature request. I have not been able to determine how to only use specific GPUs on Windows. Many / most popular miners allow choosing only specific GPUs if so desired.

Thanks!

**Comment by EggPool** [comment]
Yep,  see -i param
https://github.com/EggPool/BismuthHowto/blob/master/Mining/Miner_Version_3.md
for instance,
-i 100,0,0,0
to use first gpu of 4
of 
-i 0,0,50,50
to use 3/4 and 4/4 only.

**Comment by pricejn2** [comment]
Dang, sorry I missed that. Was actually on that md at one point and didn't catch the usage of `-i` for restricting certain gpus. Thanks for clarifying and the reference.
